name: "Run Runtime Action Deploy"
description: "Runs Runtime Action Deploy with parameters"
inputs:
  FEATURES_LEVEL_LOG:
    description: "Log Level"
    required: true
  INPUT_PATH:
    description: "Input file name"
    required: true

runs:
  using: "composite"
  steps:

    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash
      
    - name: Run Runtime Action Deploy
      run: |
        docker run --rm \
        -e FEATURES_LEVEL_LOG=${{ inputs.FEATURES_LEVEL_LOG }} \
        --entrypoint=/app/stackspot-runtime-job-deploy \
        stackspot/runtime-deploy start --input-path=${{ inputs.INPUT_PATH }}
      shell: bash

branding:
    icon: 'terminal'
    color: 'orange'